### ISSUE TITLE
Discussion: To do list

### ISSUE THREAD

**Issue by l3u** [openv/vcontrold#1]
Hi :-)

First of all, I would recommend that all development and communication is done in English. Viessmann heatings are not only sold in Germany, and if we speak German here, we probably alienate possible foreign developers. I think everybody willing to work on this code speaks at least a bit English.

So, here's what I think that has to be done, please tell me what you think:

### Moving the documentation

All wiki pages should be moved here (from openv/openv) and translated to English.

### Changing the build system

Done:-)

#### Formatting

I think the sources need a more uniform appearance, speaking of coding style (indentation etc.). I'd propose to stick to the kdelibs/Qt coding style, as this one is clean and easy to read and write.

I would firstly format all sources with
```
astyle --style=kr --add-one-line-brackets --pad-header --pad-comma --align-pointer=name --pad-oper vcontrold.c
```
and then do some fine tuning.

Same thing for the XML files. I would give them a nice and consistent look via
```
xmllint --format
```
and then do some fine tuning by hand.

At this point, nothing in the sources would have been changed, only the formatting.

#### Reworking the documentation

I would suggest to convert the manpages to something more maintainable like [ReStructuredText](http://docutils.sourceforge.net/rst.html) and then compile a manpage from them when building the package. The rst tools come with such a tool by default. I'm a big fan of rst and think it's way better than the other ones around (including Markdown).

Compiling the documentation could be made conditional via cmake. If we have the tools we need, the docs are built (and probably installed). If not, then not. I am doing this exact thing (but with a HTML conversion, not man – still, it's the very same thing) already with another of my projects and it works fine.

#### Translation

I would translate all German messages and variable names to their English counterpart. For the very same reasons I'm writing in English here (see above).

Same for manpages, readmes etc.

Probably, one should also translate the German-English mix command names of the vito.xml file (e. g. `getTempA` should be `getTempO` etc.).

### (Re-)Unify the development

We should try to collaborate with

- https://github.com/thelsing/vcontrold/
- https://github.com/probonopd/vcontrold-for-openwrt/

Someone's working on the code there, and most probably, the changes are meaningful. We should all work on the "official" code here, which finally made it out of sf/svn.

**Comment by speters** [comment]
Concerning translations of messages und names, I suggest adhering to the "official" diction of Viessmann.

At https://gist.github.com/speters/57896313e35f4593f6efa85f793690ec I posted some "hints" on how to get some great info about datapoints/addresses, their types,  names, and meanings in various languages from the Vitоѕоft demo software.
These XML files are basically sql dumps for the initial setup of an ms-sql database. https://gist.github.com/speters/6b5dfc59f7d681da8ba148a2032ecf3f shows a way how to strip the ms-specific parts for importing into an sqlite db for example.
It's just some rough scripts, but I think it's possible to get the point.

PS:
@thelsing went a similar way: he pulled his info from the db of a live installation of the beforementioned software to create his specific xml files.

**Comment by l3u** [comment]
Well, then I would leave the XML names as-is for now. I always wondered where all this came from ;-)

**Comment by l3u** [comment]
Well, I think most of this has been already done now. Much faster than I thought :-) Closing this for now.

**Comment by lolorc** [comment]
@speters would care sharing more details about the datapoints/addresses and how to get them.
It looks like your gist only extracts the database structure from DPDefinitions.xml
