### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Carto477** [openv/vcontrold#122]
At the "make" step of the below procedure, I get the following error. Compiling on Raspberry Pi 4. 

```
gcc  -g -O2   -o vclient vclient.o client.o common.o socket.o io.o  -lxml2
/usr/bin/ld: client.o:/home/pi/openv/vcontrold-code/vcontrold/client.h:30: multiple definition of `TxRx'; vclient.o:/home/pi/openv/vcontrold-code/vcontrold/client.h:30: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:409: vclient] Error 1

```
```
cd ~
mkdir openv
cd openv
svn checkout svn://svn.code.sf.net/p/vcontrold/code/trunk vcontrold-code
cd vcontrold-code/vcontrold
chmod +x auto-build.sh
./auto-build.sh
./configure
make
sudo make install
```

Thank you so much for your kind thoughts ;-)

**Comment by l3u** [comment]
First, I'd try to compile the code hosted here on GitHub (where you interestingly posted this) ;-)

The vcontrold build system has been moved to cmake back in 2017. This must be some very old code …

**Comment by Carto477** [comment]
Oh my ... | Yes, that was it (I feel a little ashamed). 
Thank you so much for your swift, and smart, answer !
