### ISSUE TITLE
unable to start vcontrold after new installation

### ISSUE THREAD

**Issue by nw378** [openv/vcontrold#143]
It's hair-raising...

Vcontrold won't start.... 

What I did: 

* set up a plain system (openhabian 64bit, bookworm, similar like before) on a Raspi 4
* renamed the USB Port 
   `sudo nano /etc/udev/rules.d/10-usb-serial.rules`
   `SUBSYSTEM=="tty", ATTRS{idProduct}=="ea60", ATTRS{idVendor}=="10c4", SYMLINK+="ttyUSB_vito"`  (similar like working system before)
* reboot
* copied **vcontrold.xml** and **vito.xml** to /etc/vcontrold/ (working backup files)
   beginning of vcontrold.xml:

![vcontrold_xml](https://github.com/user-attachments/assets/41be6e29-58c2-48c5-9095-a09677a06124)

(pasting code here causes format error)

* `sudo apt-get update`
    `sudo apt-get upgrade`
* installed vcontrold according to [https://github.com/openv/openv/wiki/vcontrold-mit-Raspberry-Pi](url)
* `wget https://github.com/openv/vcontrold/releases/download/v0.98.11/vcontrold_0.98.11-7_armhf.de`
    `sudo apt install ./vcontrold_0.98.11-7_armhf.deb `
* (also tried [https://github.com/openv/vcontrold/releases/download/v0.98.12/vcontrold_0.98.12-16_armhf.zip](url) after removal of 11-7)
*  `cd /etc/systemd/system`
    `sudo nano nano vcontrold.service`
(according to [https://github.com/openv/openv/issues/615](url) )

`[Unit]`
`Description=vcontrold for Viessmann`
`Documentation=https://github.com/openv/vcontrold`
`After=syslog.target systemd-udev-settle.service`
`[Service]`
`Type=forking`
`ExecStart=+/usr/local/sbin/vcontrold -x /etc/vcontrold/vcontrold.xml --inet4 --syslog`
`StandardOutput=inherit`
`StandardError=inherit`
`ExecReload=/bin/kill -HUP $MAINPID`
`Restart=on-failure`
`RestartSec=10`
`StartLimitBurst=5`
`#StartLimitIntervalSec=30`
`[Install]`
`WantedBy=multi-user.target
`
**I have no /home/pi/openv/startup.sh**

* `sudo chmod +x vcontrold.servive`
   `sudo systemctl daemon-reload`
   `sudo systemctl enable vcontrold`
   `sudo systemctl start vcontrold`

* also copied vcontrold to /usr/local/sbin/
* also tried vcontrold.service:

`[Unit]`
`Description=vcontrold daemon`
`After=syslog.target`

`[Service]`
`Type=forking`
`ExecStartPre=`
`ExecStart=/usr/sbin/vcontrold -x /etc/vcontrold/vcontrold.xml`
`ExecReload=/bin/kill -HUP $MAINPID`
`Restart=always`
`RestartSec=120`
`StandardOutput=null`

`[Install]`
`WantedBy=multi-user.target`
`

No matter what I try, I always get:

_Job for vcontrold.service failed because the control process exited with error code.
See "systemctl status vcontrold.service" and "journalctl -xeu vcontrold.service" for details.
_

journalctl -xeu vcontrold.service:
_
░░ Automatic restarting of the unit vcontrold.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Dez 10 17:10:04 openhabian systemd[1]: Stopped vcontrold.service - vcontrold daemon.
░░ Subject: A stop job for unit vcontrold.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A stop job for unit vcontrold.service has finished.
░░
░░ The job identifier is 19748 and the job result is done.
Dez 10 17:10:04 openhabian systemd[1]: Starting vcontrold.service - vcontrold daemon...
░░ Subject: A start job for unit vcontrold.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit vcontrold.service has begun execution.
░░
░░ The job identifier is 19748.
Dez 10 17:10:04 openhabian (controld)[19407]: vcontrold.service: Failed to execute /usr/sbin/vcontrold: No such file or directory
Dez 10 17:10:04 openhabian (controld)[19407]: vcontrold.service: Failed at step EXEC spawning /usr/sbin/vcontrold: No such file or directory
░░ Subject: Process /usr/sbin/vcontrold could not be executed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The process /usr/sbin/vcontrold could not be executed and failed.
░░
░░ The error number returned by this process is 2.
Dez 10 17:10:04 openhabian systemd[1]: vcontrold.service: Control process exited, code=exited, status=203/EXEC
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit vcontrold.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 203.
Dez 10 17:10:04 openhabian systemd[1]: vcontrold.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit vcontrold.service has entered the 'failed' state with result 'exit-code'.
Dez 10 17:10:04 openhabian systemd[1]: Failed to start vcontrold.service - vcontrold daemon.
░░ Subject: A start job for unit vcontrold.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit vcontrold.service has finished with a failure.
░░
░░ The job identifier is 19748 and the job result is failed.
_

Where is my mistake????

**Comment by speters** [comment]
The line reading
`Dez 10 17:10:04 openhabian (controld)[19407]: vcontrold.service: Failed to execute /usr/sbin/vcontrold: No such file or directory`
suggests that you check if your vcontrold binary is sitting in `/usr/sbin/vcontrold` and is executable.

Latest release is [0.98.12](https://github.com/openv/vcontrold/releases/tag/v0.98.12).

**Comment by nw378** [comment]
Moin, 

vcontrold is in /usr/sbin , too.
release 0.98.12 also tested, similar result.
setting executable is `sudo chmod -x vcontrold` ? 
done. no improvement...

[18:16:00] openhabian@openhabian:/usr/local/sbin$ sudo chmod -x vcontrold
[18:16:49] openhabian@openhabian:/usr/local/sbin$ sudo vcontrold -n
sudo: unable to execute /usr/sbin/vcontrold: No such file or directory
[18:16:56] openhabian@openhabian:/usr/local/sbin$ ls -l
insgesamt 144
-rwxr-xr-x 1 root root   6206  9. Dez 20:19 set-partuuid
-rw-rw-rw- 1 root root 115180 10. Dez 16:58 vcontrold
-rwxr-xr-x 1 root root  15057  9. Dez 20:19 zram-config
-rwxr-xr-x 1 root root     63  9. Dez 20:19 zram-sync
[18:16:59] openhabian@openhabian:/usr/local/sbin$

**Comment by l3u** [comment]
I'd start with starting `vcontrold` manually, on a console, with the `--nodaemon` option and see what it outputs. And when it runs and works in foreground, you can run it as a daemon using your init system.

Making the `vcontrold` binary non-executable doesn't seem really target-aimed though … maybe you want to RTFM `man chmod`. I'd suggest `chmod 0755` or `chmod +x`.

**Comment by nw378** [comment]
Thanks for the hint. I wasn't familiar with TFM "man" yet ;-)

What I tried:

[20:22:17] openhabian@openhabian:/usr/local/sbin$ cd /usr/local/sbin
[20:23:10] openhabian@openhabian:/usr/local/sbin$ sudo chmod 0755 vcontrold
[20:23:13] openhabian@openhabian:/usr/local/sbin$ sudo chmod +x vcontrold
[20:23:17] openhabian@openhabian:/usr/local/sbin$ vcontrold --nodaemon
-bash: /usr/local/sbin/vcontrold: cannot execute: required file not found
[20:23:20] openhabian@openhabian:/usr/local/sbin$ ls -l
insgesamt 144
-rwxr-xr-x 1 root root   6206  9. Dez 20:19 set-partuuid
-rwxr-xr-x 1 root root 115180 10. Dez 16:58 vcontrold
-rwxr-xr-x 1 root root  15057  9. Dez 20:19 zram-config
-rwxr-xr-x 1 root root     63  9. Dez 20:19 zram-sync

still no progress :-/

**Comment by l3u** [comment]
No harm meant, but if you want to do low-level stuff like setting up a daemon and running it, you maybe should become at least a little bit familiar with the basics of using a Linux system on the console …

If you type `vcontrold --nodaemon` inside `/usr/local/sbin`, you don't start a `vcontrold` file that may be located there. You try to start a `vcontrold` executable that is somewhere inside a directory listed in your `$PATH` environment variable. And it seems that `/usr/local/sbin` is not listed there. If you want to start `/usr/local/sbin/vcontrold` with `/usr/local/sbin` not being listed in `$PATH`, you either have to use the full path, i.e. `/usr/local/sbin/vcontrold`, or when you're inside `/usr/local/sbin`, you have to start `./vcontrold` (notice the `./` at the start. `.` refers to the current working directory, so `./vcontrold` refers to the file `vcontrold` inside the current working directory).

PS: `chmod 0755` and `chmod +x` do the same thing. You don't have to invoke both. Also, you maybe want to read about (GitHub) MarkDown to format your stuff here a bit, like cited code blocks and such.

**Comment by nw378** [comment]
I vow to get better, this is my very first call for help on github.

So, next trial:

`openhabian@openhabian:/$ /usr/local/sbin/vcontrold --nodaemon`
and 
`openhabian@openhabian:/usr/local/sbin$ ./vcontrold --nodaemon
`
Unfortunately, same response:

`-bash: ./vcontrold: cannot execute: required file not found`

**Comment by l3u** [comment]
So you do have `/usr/local/sbin/vcontrold`, and it's executable, i.e. `ls -l /usr/local/sbin/vcontrold` shows something like

    -rwxr-xr-x 1 root root 334K 23. Okt 07:44 /usr/local/sbin/vcontrold

… yet, you can't start it. That is indeed strange. A quick Google search for that odd "cannot execute: required file not found" lead me to [this StackExchange question](https://unix.stackexchange.com/questions/721844/linux-bash-shell-script-error-cannot-execute-required-file-not-found). Are you sure your `/usr/local/sbin/vcontrold` is actually the daemon's executable? And not some text file the shell tries to execute using a shebang interpreter that doesn't exist?

`file /usr/local/sbin/vcontrold` should output something like this:

    vcontrold: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped

**Comment by nw378** [comment]
> So you do have `/usr/local/sbin/vcontrold`, and it's executable, i.e. `ls -l /usr/local/sbin/vcontrold` shows something like
> 
> ```
> -rwxr-xr-x 1 root root 334K 23. Okt 07:44 /usr/local/sbin/vcontrold
> ```
> 
confirm:

`-rwxr-xr-x 1 root root 115180 10. Dez 16:58 /usr/local/sbin/vcontrold
`
> … yet, you can't start it. That is indeed strange. A quick Google search for that odd "cannot execute: required file not found" lead me to [this StackExchange question](https://unix.stackexchange.com/questions/721844/linux-bash-shell-script-error-cannot-execute-required-file-not-found). Are you sure your `/usr/local/sbin/vcontrold` is actually the daemon's executable? And not some text file the shell tries to execute using a shebang interpreter that doesn't exist?

yes, it's not a shebang:
> 
> `file /usr/local/sbin/vcontrold` should output something like this:
> 
> ```
> vcontrold: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped
> ```

`/usr/local/sbin/vcontrold: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=0bd5142684de77b379f081456bac242bc633899c, for GNU/Linux 3.2.0, not stripped`

That's was the necessary hint. **armhf** is the wrong version, I need **ARM64** instead. 

I tried it before, but got an error. so I used the one from the orginal github discription. 

Solved, thanks a lot for your help and patience with a noob ;)

**Comment by l3u** [comment]
You're welcome :-) Nice you could get it to work!

**Comment by l3u** [comment]
PS: I personally would highly recommend using Alpine Linux on a Raspberry Pi, esp. if it's a dedicated machine to only communicate with your heating. It's invigoratingly simple and minimalist. The installation and maintenance is really, really easy. And you don't have to deal with that Systemd bulls**t, because it uses Gentoo's outstanding OpenRC as the init system.

An OpenRC init script for vcontrold is as simple as

    #!/sbin/openrc-run
    command="/usr/local/sbin/vcontrold"

I have been running a Raspberry Pi 1 connected to my heating for almost 10 years now, and I switched to Alpine last year (after having used Gentoo and Devuan before). Works like a charm, and the whole system runs on an old 4 GB SD card, with 380 M used.
