### ISSUE TITLE
Tagging a "real" release

### ISSUE THREAD

**Issue by l3u** [openv/vcontrold#18]
Apparently, the rework is okay, ahd some other stuff has been fixed as well?

What about tagging and creating a "real" release? E. g. with version number 0.99? I was working on a Gentoo ebuild for vcontrold, and it would of course be much nicer to reference a real release than some git ID.

What do you think?

**Comment by speters** [comment]
IMO reserve the bump to a new minor version when the xml configs are sorted out, and advance the patch level instead.

**Comment by l3u** [comment]
Would be just as fine.

**Comment by hmueller01** [comment]
It's good to tag this state. We made no functional enhancements only bug fixes and code style fixing, so I would prefer a minor release too.

**Comment by speters** [comment]
I finally managed to set up Travis CI with cross-compilation for armhf and a very basic deployment to GitHub releases.

Tagged v0.98.4

**Comment by l3u** [comment]
You forgot to add a `version.h` file with the correct version hard-coded – the tarball won't compile due to this file not being there …

**Comment by l3u** [comment]
cmake should generate a dummy `version.h` in this case though …

**Comment by l3u** [comment]
At least, not building a `version.h` file in each case should be fixed with commit 9f08fb2. We need another (bugfix) release though – the released tarball will fail compiling as said.

**Comment by l3u** [comment]
Thanks, for re-releasing the tarball! But the version is still set to "unknown" through the fallback. I thought it was possible to add manually created files to releases hosted on github? If not, we should add a version.h file with the last release version (which will be overwritten by the cmake function), or we always have "unknown" as the version when using tarballs. Distributors (at least Gentoo ;-) don't like git clones, they want tarballs to be put on mirrors.

**Comment by speters** [comment]
Ah, ok. I got you now.
It is possible to add files to GitHub releases, but the zipped/tarred source archives provided by GitHub can not be overridden or deleted.

What about deriving the version from the path name of the source directory? 
In GitHubs source archives, the sources are located in a `reponame-tagnamewithoutv` directory (e.g. in `vcontrold-0.98.4` .
This seems consistent with the Gentoo and the Debian naming scheme.

**Comment by l3u** [comment]
Isn't it possible to do a "real" release including the version.h file and provide it? And leave the Github generated ones out? I mean, it would work in this case, but we're solving a problem that only exists because Github auto-generates tarballs, and we would not have this problem if a real release was hosted somewhere else …

**Comment by speters** [comment]
The releases deployed via TravisCI now include
 * a tar.gz of the sources (_with_ src/version.h)
 * checksum files (per archive, due to the way the build matrix of Travis CI works)
 * Debian deb binary packages (via checkinstall)
