### ISSUE TITLE
Sticky Bit not set for vcontrold

### ISSUE THREAD

**Issue by emichel11** [openv/vcontrold#20]
After 
   _make
   sudo make install_
the vcontrold and vclient are build and installed.
The vcontrold is copied into "_usr/local/sbin_"
if vcontrold runs as daemon it tries to create a PID lock file in 
_/var/run/vcontrold.pid_
However if the sticky bit is not set the code in vcontrold.c
_sid = setsid();_
has not effect and there might not be enough rights to create the PID file.
This happens especially when one creates a service file for systemctl
As a workaround set the sticky bit manually
_sudo chmod +s /usr/local/sbin/vcontrold_

As an improvement change "_make install_" appropriately.

**Comment by l3u** [comment]
I don't fully understand why you want to set the sticky bit here … normally  you only use it for folders nowadays?

I have vcontrold installed on my Raspberry Pi running Gentoo. No sticky bit is set, and vcontrold is started using OpenRC and a minimal init script. Runs just fine!

Probably, this is distribution specific for your case?

**Comment by emichel11** [comment]
Hello Tobias,
sorry for the late reply.
generally you are right. vcontrold works as expected - if you start it as "root".
If you run it as ordinary user vcontrold has usually no access to _/var/log/_ and therefore cannot touch the file _vcontrold.pid_ - it will fail to start.
My request should be seen as an improvement with low priority.

**Comment by speters** [comment]
Fixed by https://github.com/openv/vcontrold/pull/21
