### ISSUE TITLE
make DESTDIR=/usr/local install fails

### ISSUE THREAD

**Issue by hmueller01** [openv/vcontrold#27]
Gets installed in `/usr/local/usr/local/...`
```
pi ~/src/vcontrold/build $ sudo make DESTDIR=/usr/local install
[  5%] Updating version header.
-- Updating version information to 0.98.5-4-gf3e0f20 ...
[  5%] Built target UpdateVersion
[ 35%] Built target vclient
[ 90%] Built target vcontrold
[100%] Built target man
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/usr/local/sbin/vcontrold
-- Installing: /usr/local/usr/local/bin/vclient
-- Installing: /usr/local/usr/local/share/man/man1/vcontrold.1.gz
-- Installing: /usr/local/usr/local/share/man/man1/vclient.1.gz
```

**Comment by speters** [comment]
According to https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html this is the desired behaviour of cmake.

Use `CMAKE_INSTALL_PREFIX` variable instead.

**Comment by hmueller01** [comment]
You are right. But then [INSTALL.md](https://github.com/openv/vcontrold/blob/master/doc/INSTALL.md) is a bit misleading. Maybe it is better to remove the `DESTDIR` note. The `CMAKE_INSTALL_PREFIX` works as expected.

**Comment by hmueller01** [comment]
I think this line should look like
`cmake -DVSIM=ON -DMANPAGES=OFF -DCMAKE_INSTALLATION_PREFIX=/usr/local ..`
instead of
`cmake -DVSIM=ON -DMANPAGES=OFF -DCMAKE_INSTALLATION_PREFIX=/usr/local ...`
