### ISSUE TITLE
Error in manpage about the serial-device option?

### ISSUE THREAD

**Issue by l3u** [openv/vcontrold#29]
According to the manpage, the device file to use can be set using the `<serial-device>` tag. I currently have:

    <serial>
        <tty>/dev/ttyAMA0</tty>
    </serial>

If I change it to

    <serial-device>/dev/ttyAMA0</serial-device>

vcontrold crashes with a segfault. Looking into the sources, the xml config apparently does not know about a `serial-device` tag. If this is actually the case, we either should process this tag (which would be a meaningful thing imo, as the current `serial` tag is apparently always followed by a `tty` tag and nothing else, so exchaning this for a `serial-device` tag would be less complicated), or we should change the manpage.

I just didn't want to correct the manpage without asking first if I'm correct.

Cheers, Tobias

**Comment by speters** [comment]
The values for command line options are supplied as values, not as XML-ish tags.
The bracket quotes / guillemets in the manual are used to denote where a value must be supplied.

Feel free to propose a better typographical way which renders well on both RST, and man (take into account that a manpage might also become displayed as plain text (no bold,underline, ...)).
