### ISSUE TITLE
how to update installed version to the latest 

### ISSUE THREAD

**Issue by passuff** [openv/vcontrold#41]
I'm new to this stuff and glad to have vcontrold running but is there a way to update vcontrold easily without loosing all the adjustments?

**Comment by speters** [comment]
User-configurable adjustments are in the xml files. So you should make sure you keep a backup.

The program files _vcontrold_ and _vclient_ can be simply replaced with a newer version (either by manual replacement, `make install` or by installing a newer [deb package](https://github.com/openv/vcontrold/releases)). 
During installation, _/usr/share/doc/vcontrold_ gets written, so don't use this location to store your edited configs (wouldn't be the right place anyway).

The provided deb packages are dead-simple (just installing the plain files) and provide no means of a start-stop procedure for the daemon, or taking care of config locations or edits.

You need to restart the _vcontrold_ daemon after having updated/changed its binary.
