### ISSUE TITLE
Runtime für Windows

### ISSUE THREAD

**Issue by s4ndst0rm** [openv/vcontrold#46]
Hallo!

Gibt es eine Möglichkeit vcontrold und vclient unter Windows laufen zu lassen?
Mit cygwin kommt ein Fehler 7b und es läuft nicht.

Gibt es evtl ein neues binary?

**Comment by speters** [comment]
Im  [Releases Bereich](https://github.com/openv/vcontrold/releases) sind nun Binaries für den Betrieb in einer **cygwin**  Installation verfügbar. Die Releases werden automatisch gebaut und sind ungetestet.
Feedback gerne hier in den Issues posten.

There are now **cygwin** builds in the [releases section](https://github.com/openv/vcontrold/releases).
Feedback appreciated.
