### ISSUE TITLE
Vcontrold without dependency on libxml2 as shared library?

### ISSUE THREAD

**Issue by jansauerbrey** [openv/vcontrold#48]
Hi,

I'm trying to get vcontrold running on a Homematic CCU3 which is raspbian based. However if I use the precompiled binaries from the release page, I run into the missing library libxml2.so.2

vcontrold: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory

Without being an expert in compiling, is there a easy way to incorporate these libraries into vcontrold directly?

Thanks for any hints in the right direction.

Jan

**Comment by speters** [comment]
Install `libxml2` via the package manager of your Linux distribution.

On _Raspbian_ and similar Debian-based systems, this is done via
`sudo apt install libxml2`

**Comment by jansauerbrey** [comment]
I tried that already, but this is an issue, since the CCU3 does not have a package manager. The OS is actually the original CCU3 firmware. However one can copy addons and that way I tried to install vcontrold.

Unless you know a good way or source to install libxml2 on this platform, I thought it might be easier to recompile it without external dependencies (if that is at all possible).

**Comment by speters** [comment]
If it is raspbian based, just copy over the files of the appropriate libxml2 package over to your platform (e.g. extract them from the deb package).
The entire vcontrold is too flawed to make a transition to a smaller, embeddable library worthwile-
