### ISSUE TITLE
Idea: Port to Sub-3 EUR WLAN device

### ISSUE THREAD

**Issue by probonopd** [openv/vcontrold#6]
The _Wemos D1 Mini_ is a Sub-3 EUR [ESP8266](https://en.wikipedia.org/wiki/ESP8266) device with integrated WLAN. It can be programmed in C++/Arduino: https://github.com/esp8266/Arduino

I wonder whether vcontrold could be ported there.

**Comment by speters** [comment]
IMO vcontrold is not suited for devices, where RAM is very scarce.
Have a look at e.g. https://github.com/bertmelis/VitoWifi or use https://github.com/jeelabs/esp-link as a "ser2net"/"socat" Optolink->network link to a remote vcontrold.

**Comment by probonopd** [comment]
Interesting, thank you.
