### ISSUE TITLE
newbie problem: access to USB device quits daemon

### ISSUE THREAD

**Issue by createch2** [openv/vcontrold#61]
I followed the instructions here:
https://github.com/openv/openv/wiki/vcontrold-mit-Raspberry-Pi

And I struggle on several points:
- i cannot found any "serial_short" number on my USB adapter
- I can use id_product instead, this seems also be a unique number, my file 70-lesekopf.rules looks then like:
SUBSYSTEMS=="usb", ATTRS{idProduct}=="7523", SYMLINK+="vitoir0"

but still the telnet session gets closed by a simple getTempA:

looks then like this:

vctrld>debug on
vctrld>getTempA
DEBUG:Thu Oct 18 07:03:14 2018 : Befehl: getTempA
DEBUG:Thu Oct 18 07:03:14 2018 : Process 1899 tries to aquire lock
DEBUG:Thu Oct 18 07:03:14 2018 : Process 1899 got lock
DEBUG:Thu Oct 18 07:03:14 2018 : >FRAMER: open device t: ST ProtocolID 00
DEBUG:Thu Oct 18 07:03:14 2018 : Fehler getaddrinfo: t:Name or service not known
Connection closed by foreign host.

Can someone help me to fix that?

**Comment by speters** [comment]
The German output in your log file looks like you are running an old version of `vcontrold`.
Please update to the latest version and report back if the problem persists.

----

Die deutschen Log-Ausgaben lassen erahnen, dass du eine alte Version von `vcontrold` betreibst.
Bitte update auf die aktuellste Version und melde dich gerne, wenn das Problem weiter besteht.
