### ISSUE TITLE
Meaning of "SYNC (NOT OK)" return status?

### ISSUE THREAD

**Issue by DBa2016** [openv/vcontrold#68]
Hi guys,

when trying to set warm water temperature (setTemWWsoll) on my Vitodens200, I am receiving a "SYNC (NOT OK)" result. What is the meaning of this return code?

Thanks in advance
Best regards
DBa

**Comment by speters** [comment]
It means your `vcontrold` received a 0x05 (==SYNC) byte sequence, but expected something different (e.g. a 0x06 (==ACK)).

If your XML is configured correctly (I think setting WW temp for your device is at address 0x6300 as in the default XML), then maybe you tried to set a WW temp. outside the correct range.

There are 2 possible ranges: 10..60°C and 10..90°C.
The range is coded at address 0x6756 with "0" being the 10..60°C range and "1" being 10..90°C.

**Comment by hmueller01** [comment]
I just tried with latest git version (vcontrold version 0.98.9-8-gae6873e):
```
vctrld>getTempWWSoll
50.000000 Grad Celsius
vctrld>setTempWWSoll 49
OK
vctrld>getTempWWSoll
49.000000 Grad Celsius
vctrld>setTempWWSoll 50
OK
vctrld>getTempWWSoll
50.000000 Grad Celsius
vctrld>
```
Maybe you can try this as well.
