### ISSUE TITLE
vcontrold.log auto delete needed

### ISSUE THREAD

**Issue by passuff** [openv/vcontrold#69]
I checked vcontrold.log after almost two years and its filesize grew to more than 6Gb. Is there an option what should be logged or an auto delete?

**Comment by speters** [comment]
Usually, a tool like "logrotate" is run via a cron job to take care of this.

> **logrotate** is designed to ease administration of systems that generate large numbers of log
       files.  It allows automatic rotation, compression, removal,  and  mailing  of  log  files.
       Each log file may be handled daily, weekly, monthly, or when it grows too large.
