### ISSUE TITLE
Cant set temperature for M2 | no Option to set temperature

### ISSUE THREAD

**Issue by Snotmann** [openv/vcontrold#71]
Hey guys,

the vcontrold runs fine but i cant set the room temperature für my M2 circuit:

vclient -c 'setTempRaumNorSollM2 22'
SRV ERR: command unknown
setTempRaumNorSollM2 22:
server error

... there was no option for it in the vito.xml.

Try to create it myself withoput luck :(

**Comment by hmueller01** [comment]
You do not have a command `setTempRaumNorSollM2` defined in your `vito.xml`?
To check what commands are known use

`vclient -c commands`

BTW: This does not look like a vcontrold bug. If you have questions how to setup your xml files, please take a look [here](https://github.com/openv/openv/wiki). There is another issue tracker.
