### ISSUE TITLE
vclient sends additional error note

### ISSUE THREAD

**Issue by vito-user** [openv/vcontrold#79]
Hi,
If I am using the command line prompt of vcontrold I get a correct communication:

```
pi@raspberrypi:~ $ telnet localhost 3002
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
vctrld>getVitoTempAussen
6.200000 °C
vctrld>
```

But if I do it with vclient I get always such error information. Finally I get also the requested value.
Because I have problems to move values in RRDB I assume it can be a reason.

```
pi@raspberrypi:~ $ vclient -h 127.0.0.1 -p3002 - c getVitoTempAussen
SRV ERR: command unknown
SRV ERR: command unknown
-:
server error
c:
server error
getVitoTempAussen:
6.200000 °C
pi@raspberrypi:~ $
```

I have already changed the protocol KW2 to P300. But it is the same. Does somebody has an idea?
Regards, Uwe

**Comment by speters** [comment]
You supplied " - c" as command line arguments.
Try "-c"  (no space) or just leave it out and add your commands to the tail of you command line arguments.

**Comment by vito-user** [comment]
Hi speters, Thanks for the eye-opener. This was realy a stupid typing mistake. But now it works.
