### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by R3play13** [openv/vcontrold#87]
When i want do update to the 0.98.10 with the „ sudo apt install ./vcontrold_0.98.10-176_armhf.deb “ command, i get the message that it is on the latest version.

I use a Raspberry Pi zero.

When i check the Version with telnet it gives 0.98.2 … can anybody help me?

I saw the closed issue, but i don‘t understand the instructions to solve it.

**Comment by speters** [comment]
`apt install [{=pkg_version_number | /target_release}]... ` operates on your configured package repositories, not on your file system.

The command `sudo dpkg -i ./vcontrold_0.98.10-176_armhf.deb` should do what you desire.

**Comment by speters** [comment]
The latest binary `vcontrold` from the releases comes with version info `0.98.10` and gets installed as `/usr/sbin/vcontrold`.
The Debian Package is created via `checkinstall`, and contains nothing more than vcontrold, vclient and man pages/docs (no init script, no systemd stuff). 

Please make sure you have no stray `vcontrold` binary (e.g. in /usr/local/sbin) which got started.

**Comment by R3play13** [comment]
So....

I located another vcontrold binary in /usr/local/sbin and in openv/vcontrold-code/vcontrold.

After i remove the one in /usr/local/sbin and restart, i can't start vcontrold anymore and i get an Error "Speicherzugriffsfehler".

When i put in the oiriginal vcontrold into /usr/local/sbin from my backup i can start it normally again.

In /etc/init.d/vcontrol is saw that the path was /usr/local/sbin, i changed it to /usr/sbin...

Now it starts with the original Vcontrold binary in /usr/sbin.

But with the updated binary i get the "Speicherzugriffsfehler"

**Comment by speters** [comment]
Sorry, I overlooked your "Pi Zero".
Please try to build the package by yourself, as the one provided in the releases section is for "armhf", which the Pi Zero [isn't fully compatible](https://wiki.debian.org/RaspberryPi#Raspberry_Pi_1_.28A.2C_B.2C_A.2B-.2C_B.2B-.2C_Zero.2C_Zero_W.29) with.

The build process is documented in [doc/INSTALL.md](https://github.com/openv/vcontrold/blob/master/doc/INSTALL.md).
To keep dependences sparse, you can use ` cmake -DMANPAGES=OFF ..` to omit the generation of manual pages (which makes use of `rst2man`).

**Comment by R3play13** [comment]
Okay,

sorry but i never done something with make before… so i go to /openv/ vcontrold-code/vcontrold and do „ mkdir build…cd build… cmake -DMANPAGES=off  … sudo make install“ ?

sorry im a Noob…

**Comment by speters** [comment]
You have to install the required packages beforehand (`sudo apt install build-essential cmake libxml2-dev`).
Then it is as simple as you said:
```
cd vcontrold-sourcedir
mkdir build
cd build
cmake -DMANPAGES=off  ..
make
```
After the build process you could do a `make install` or you can copy `vcontrold` and `vclient` manually to their locations.

**Comment by R3play13** [comment]
Thanks for the quick and detailed help!

Works without Problems. ;-)
