### ISSUE TITLE
Move to SPDX copyright headers

### ISSUE THREAD

**Issue by l3u** [openv/vcontrold#89]
Hi all!

We use the long-known GPL copyright headers here, and those only for the C and header files.

Seems like nowadays, it's more common to use the [SPDX](https://spdx.dev/) copyright header approach, along with the needed license text files. And this not only for the sources, but ideally for all files in a project (at least, we do so for KDE projects).

If nobody has an objection against it, I would change the copyright headers of the sources and the cmake scripts and add a `LICENSES` folder, so that there's already a template and other contributors can start to license their files correctly and add them to existing headers where this is appropriate.

I just wanted to ask, beacuse this will touch each source file and others.

What do you think?

**Comment by speters** [comment]
It makes sense, but I'm not totally sure of the implications of doing this.

Can you safely and thorougly assume a specific legal status for each and every file and assign it via SPDX on behalf of the copyright holder?

**Comment by l3u** [comment]
Well, I would start with adding headers for the files that already have headers (the .c and .h files, simply converting the headers). We know the license here. I would also add headers to the file I wrote and added (as I'm the original author: The cmake files, like at KDE with a 3-clause-BSD license). Additionally, I would define all documentation files (incl. e.g. README.md) as CC-BY-SA-4.0. Stuff like .gitignore can be CC0-1.0, without a copyright holder.

I think this would be okay so far. For the .c and .h files, we should name an author nevertheless, as something like "The original vcontrold team" is not really okay from a legal point of view. I think Frank Nobis was the original author (wasn't he?!), so I would put his very name there. Same for the manpages (I converted them to RST, but originally, I think it also was fnobis who wrote them).

For all other contributed files, it's finally up to the contributor that added it to define a license. We can check who added them, but we can't guess the license.

This way, a lot of files in this project can get a safe licensing, whereas most of them don't have any by now (which means "all rights reserved").

At least for the files I added and the .c and .h files, I think we're safe.

**Comment by l3u** [comment]
I think I'll start with the stuff I added. As a template. Also, for these files, we can be sure, it's perfectly legally safe.

**Comment by l3u** [comment]
Okay. For the manpages, we actually have Frank Nobis as the initial author, cf. https://sourceforge.net/p/vcontrold/code/HEAD/tree/trunk/vcontrold/vcontrold.1

I don't think one can even license a manpage as GPLv3, as stated now (also, this was not mentioned in the original manpage) …

**Comment by l3u** [comment]
I wrote some emails with Frank Nobis. He's the only original author we know an email address and the real name of. According to what he told me, I updated the manpage license headers, and the headers of the source code files. Sadly, the other original authors remain only nicknames …
